<!DOCTYPE html>
<html>
	<head>
		<title>Rose Cheney</title>
	</head>
	<body>
		<nav>
    		<ul>
        		<li><a href="/">Home</a></li>
	        	<li><a href="/about">About</a></li>
        		<li><a href="/cv">CV</a></li>
    		</ul>
		</nav>
		<div class="container">
    		<div class="blurb">
        		<h1>Hi there, I'm Rose Cheney! </h1>
				<p>I'm an undergraduate senior at George Washington University <em>A Touch of Evil</em> I'm majoring in biology with a concentration in ecology, evolution, and the environment. <a href="/about">Read more...</a></p>
    		</div><!-- /.blurb -->
		</div><!-- /.container -->
		<footer>
    		<ul>
        		<li><a href="mailto:cheneyr@gwu.edu">email</a></li>
        		<li><a href="https://github.com/cheneyr">github.com/cheneyr</a></li>
			</ul>
		</footer>
	</body>
</html>

theme: jekyll-theme-cayman
